# -*- coding: utf-8 -*-
"""
Définition des 22 types de contrats (champs + clauses) — données v12.
Séparé de la logique pour garder contract_service.py lisible.
"""
from datetime import datetime

_TODAY = datetime.now().strftime("%d/%m/%Y")

CONTRACT_TYPES = {
    "عقد كراء سكني": {
        "keywords": ["كراء", "سكني", "شقة", "منزل", "location", "rent"],
        "fields": [
            {"name": "nom_mocri", "label": "الإسم الكامل للمكري", "type": "text", "required": True},
            {"name": "cin_mocri", "label": "رقم بطاقة تعريف المكري", "type": "text", "required": True},
            {"name": "adresse_mocri", "label": "عنوان المكري", "type": "text", "required": True},
            {"name": "nom_moctari", "label": "الإسم الكامل للمكتري", "type": "text", "required": True},
            {"name": "cin_moctari", "label": "رقم بطاقة تعريف المكتري", "type": "text", "required": True},
            {"name": "adresse_moctari", "label": "عنوان المكتري", "type": "text", "required": True},
            {"name": "adresse_logement", "label": "عنوان السكن المستأجر", "type": "text", "required": True},
            {"name": "description_logement", "label": "وصف السكن (المرافق)", "type": "text", "required": False},
            {"name": "loyer_mensuel", "label": "مبلغ الكراء الشهري (درهم)", "type": "number", "required": True},
            {"name": "caution", "label": "مبلغ الضمان (درهم)", "type": "number", "required": True},
            {"name": "date_debut", "label": "تاريخ بداية العقد", "type": "date", "required": True},
            {"name": "duree", "label": "مدة العقد (بالأشهر)", "type": "number", "required": True},
            {"name": "date_contrat", "label": "تاريخ العقد", "type": "date", "required": True, "default": _TODAY},
            {"name": "lieu_contrat", "label": "مكان توقيع العقد", "type": "text", "required": True},
        ],
        "clauses": ["موضوع العقد", "معاينة وتسليم المحل", "مدة الكراء", "السومة الكرائية وكيفية الأداء",
                    "واجبات السنديك والمرافق", "الضمانة", "التحملات الجبائية والضريبية", "الغرض من الكراء",
                    "الصيانة والإصلاحات", "التزامات وشروط عامة", "عناوين المراسلة", "إقرار بالرضا والأهلية"],
    },
    "عقد وكالة تجارية": {
        "keywords": ["وكالة", "تجارية", "وكيل", "موكل", "commission", "agency"],
        "fields": [
            {"name": "nom_moukil", "label": "الإسم الكامل للموكل", "type": "text", "required": True},
            {"name": "cin_moukil", "label": "رقم تعريف الموكل", "type": "text", "required": True},
            {"name": "adresse_moukil", "label": "عنوان الموكل", "type": "text", "required": True},
            {"name": "nom_wakil", "label": "الإسم الكامل للوكيل التجاري", "type": "text", "required": True},
            {"name": "cin_wakil", "label": "رقم تعريف الوكيل", "type": "text", "required": True},
            {"name": "adresse_wakil", "label": "عنوان الوكيل", "type": "text", "required": True},
            {"name": "objet_contrat", "label": "موضوع العقد (المنتجات/الخدمات)", "type": "text", "required": True},
            {"name": "region_geographique", "label": "المنطقة الجغرافية المحددة", "type": "text", "required": True},
            {"name": "commission_pourcentage", "label": "نسبة العمولة (%)", "type": "number", "required": True},
            {"name": "duree_contrat", "label": "مدة العقد (بالأشهر)", "type": "number", "required": True},
            {"name": "date_contrat", "label": "تاريخ العقد", "type": "date", "required": True, "default": _TODAY},
            {"name": "lieu_contrat", "label": "مكان توقيع العقد", "type": "text", "required": True},
        ],
        "clauses": ["موضوع العقد", "تنفيذ العقد", "النطاق الجغرافي والزبناء", "الحصرية", "التزامات الموكل",
                    "التزامات الوكيل", "العمولة (الأجرة)", "مصاريف تنفيذ الصفقات", "تقديم الحساب",
                    "العمليات المستوجبة للموافقة المسبقة", "السر المهني وحماية المعلومات", "مدة العقد", "الفسخ المبكر"],
    },
    "عقد عمل": {
        "keywords": ["عمل", "شغل", "استخدام", "أجير", "employé", "travail"],
        "fields": [
            {"name": "nom_employeur", "label": "الإسم الكامل للمشغل", "type": "text", "required": True},
            {"name": "cin_employeur", "label": "رقم تعريف المشغل", "type": "text", "required": True},
            {"name": "adresse_employeur", "label": "عنوان المشغل", "type": "text", "required": True},
            {"name": "nom_salarie", "label": "الإسم الكامل للأجير", "type": "text", "required": True},
            {"name": "cin_salarie", "label": "رقم بطاقة تعريف الأجير", "type": "text", "required": True},
            {"name": "adresse_salarie", "label": "عنوان الأجير", "type": "text", "required": True},
            {"name": "poste", "label": "المنصب أو الوظيفة", "type": "text", "required": True},
            {"name": "salaire_brut", "label": "الأجر الإجمالي الشهري (درهم)", "type": "number", "required": True},
            {"name": "date_embauche", "label": "تاريخ الشروع في العمل", "type": "date", "required": True},
            {"name": "duree_contrat", "label": "مدة العقد (محدد/غير محدد)", "type": "text", "required": True},
            {"name": "periode_essai", "label": "مدة التجربة (بالأشهر)", "type": "number", "required": False},
            {"name": "date_contrat", "label": "تاريخ العقد", "type": "date", "required": True, "default": _TODAY},
            {"name": "lieu_contrat", "label": "مكان توقيع العقد", "type": "text", "required": True},
        ],
        "clauses": ["موضوع العقد", "مدة العقد", "المهام والمسؤوليات", "الأجر والمزايا", "ساعات العمل",
                    "العطل والإجازات", "التجربة", "الإنهاء والإشعار المسبق", "السرية المهنية", "التزامات الأطراف"],
    },
    "عقد بيع": {
        "keywords": ["بيع", "شراء", "مبيع", "ثمن", "vente", "achat"],
        "fields": [
            {"name": "nom_vendeur", "label": "الإسم الكامل للبائع", "type": "text", "required": True},
            {"name": "cin_vendeur", "label": "رقم بطاقة تعريف البائع", "type": "text", "required": True},
            {"name": "adresse_vendeur", "label": "عنوان البائع", "type": "text", "required": True},
            {"name": "nom_acheteur", "label": "الإسم الكامل للمشتري", "type": "text", "required": True},
            {"name": "cin_acheteur", "label": "رقم بطاقة تعريف المشتري", "type": "text", "required": True},
            {"name": "adresse_acheteur", "label": "عنوان المشتري", "type": "text", "required": True},
            {"name": "objet_vente", "label": "وصف الموضوع المبيع", "type": "text", "required": True},
            {"name": "prix_vente", "label": "ثمن البيع (درهم)", "type": "number", "required": True},
            {"name": "mode_paiement", "label": "طريقة الدفع", "type": "text", "required": True},
            {"name": "date_vente", "label": "تاريخ عقد البيع", "type": "date", "required": True},
            {"name": "delai_livraison", "label": "مدة التسليم", "type": "text", "required": False},
            {"name": "garantie", "label": "شروط الضمان", "type": "text", "required": False},
            {"name": "date_contrat", "label": "تاريخ العقد", "type": "date", "required": True, "default": _TODAY},
            {"name": "lieu_contrat", "label": "مكان توقيع العقد", "type": "text", "required": True},
        ],
        "clauses": ["موضوع البيع", "الثمن وشروط الدفع", "تسليم المبيع", "الضمانات", "المسؤولية", "شروط الإلغاء"],
    },
    "نظام أساسي SARL": {
        "keywords": ["sarl", "شركة", "تأسيس", "مسؤولية محدودة", "statuts", "société"],
        "fields": [
            {"name": "nom_societe", "label": "الإسم التجاري للشركة", "type": "text", "required": True},
            {"name": "capital_social", "label": "رأس المال الاجتماعي (درهم)", "type": "number", "required": True},
            {"name": "nombre_parts", "label": "عدد الحصص الاجتماعية", "type": "number", "required": True},
            {"name": "valeur_part", "label": "قيمة الحصة الواحدة (درهم)", "type": "number", "required": True},
            {"name": "siege_social", "label": "عنوان المركز الاجتماعي", "type": "text", "required": True},
            {"name": "objet_social", "label": "الغرض الاجتماعي (النشاط)", "type": "text", "required": True},
            {"name": "gerant", "label": "الإسم الكامل للمدير المسير", "type": "text", "required": True},
            {"name": "cin_gerant", "label": "رقم بطاقة تعريف المدير", "type": "text", "required": True},
            {"name": "adresse_gerant", "label": "عنوان المدير", "type": "text", "required": True},
            {"name": "nationalite_gerant", "label": "جنسية المدير", "type": "text", "required": True},
            {"name": "duree_societe", "label": "مدة الشركة (بالسنوات)", "type": "number", "required": True},
            {"name": "associes", "label": "أسماء الشركاء المؤسسين", "type": "text", "required": True},
            {"name": "date_contrat", "label": "تاريخ العقد", "type": "date", "required": True, "default": _TODAY},
            {"name": "lieu_contrat", "label": "مكان توقيع العقد", "type": "text", "required": True},
        ],
        "clauses": ["الشكل القانوني", "التسمية التجارية", "الغرض الاجتماعي", "المقر الاجتماعي", "مدة الشركة",
                    "رأس المال والحصص", "زيادة وتخفيض رأس المال", "الحصص الاجتماعية", "تنازل الحصص",
                    "التسيير والصلاحيات", "قرارات الشريك الوحيد", "السنة المالية والأرباح", "الرقابة",
                    "التحويل والانحلال", "التصفية"],
    },
    "نظام أساسي SARL AU": {
        "keywords": ["sarl au", "شريك وحيد", "ش.م.م.و", "associé unique"],
        "fields": [
            {"name": "nom_societe", "label": "الإسم التجاري للشركة", "type": "text", "required": True},
            {"name": "capital_social", "label": "رأس المال الاجتماعي (درهم)", "type": "number", "required": True},
            {"name": "nombre_parts", "label": "عدد الحصص الاجتماعية", "type": "number", "required": True},
            {"name": "valeur_part", "label": "قيمة الحصة الواحدة (درهم)", "type": "number", "required": True},
            {"name": "siege_social", "label": "عنوان المركز الاجتماعي", "type": "text", "required": True},
            {"name": "objet_social", "label": "الغرض الاجتماعي (النشاط)", "type": "text", "required": True},
            {"name": "associe_unique", "label": "الإسم الكامل للشريك الوحيد", "type": "text", "required": True},
            {"name": "cin_associe", "label": "رقم بطاقة تعريف الشريك الوحيد", "type": "text", "required": True},
            {"name": "adresse_associe", "label": "عنوان الشريك الوحيد", "type": "text", "required": True},
            {"name": "nationalite_associe", "label": "جنسية الشريك الوحيد", "type": "text", "required": True},
            {"name": "gerant", "label": "الإسم الكامل للمدير المسير", "type": "text", "required": True},
            {"name": "cin_gerant", "label": "رقم بطاقة تعريف المدير", "type": "text", "required": True},
            {"name": "duree_societe", "label": "مدة الشركة (بالسنوات)", "type": "number", "required": True},
            {"name": "date_contrat", "label": "تاريخ العقد", "type": "date", "required": True, "default": _TODAY},
            {"name": "lieu_contrat", "label": "مكان توقيع العقد", "type": "text", "required": True},
        ],
        "clauses": ["الشكل القانوني", "التسمية التجارية", "الغرض الاجتماعي", "المقر الاجتماعي", "مدة الشركة",
                    "رأس المال والحصص", "زيادة وتخفيض رأس المال", "الحصص الاجتماعية", "تنازل الحصص",
                    "التسيير والصلاحيات", "قرارات الشريك الوحيد", "السنة المالية والأرباح", "الرقابة",
                    "التحويل والانحلال", "التصفية"],
    },
    "فسخ عقد كراء": {
        "keywords": ["فسخ", "إنهاء", "كراء", "إفراغ", "résiliation", "location"],
        "fields": [
            {"name": "nom_mocri", "label": "الإسم الكامل للمكري", "type": "text", "required": True},
            {"name": "cin_mocri", "label": "رقم بطاقة تعريف المكري", "type": "text", "required": True},
            {"name": "nom_moctari", "label": "الإسم الكامل للمكتري", "type": "text", "required": True},
            {"name": "cin_moctari", "label": "رقم بطاقة تعريف المكتري", "type": "text", "required": True},
            {"name": "adresse_logement", "label": "عنوان المحل موضوع الكراء", "type": "text", "required": True},
            {"name": "date_contrat_original", "label": "تاريخ عقد الكراء الأصلي", "type": "date", "required": True},
            {"name": "montant_caution", "label": "مبلغ الضمان المسترد (درهم)", "type": "number", "required": True},
            {"name": "date_contrat", "label": "تاريخ الفسخ", "type": "date", "required": True, "default": _TODAY},
            {"name": "lieu_contrat", "label": "مكان توقيع الفسخ", "type": "text", "required": True},
        ],
        "clauses": ["فسخ العلاقة الكرائية", "استرجاع الحيازة ومعاينة العقار", "براءة الذمة المالية",
                    "استرداد مبلغ الضمان", "التنازل العام والإبراء النهائي"],
    },
    "إنذار بأداء السومة الكرائية": {
        "keywords": ["إنذار", "أداء", "سومة", "كرائية", "تماطل", "mise en demeure"],
        "fields": [
            {"name": "nom_mocri", "label": "الإسم الكامل للمكري", "type": "text", "required": True},
            {"name": "cin_mocri", "label": "رقم بطاقة تعريف المكري", "type": "text", "required": True},
            {"name": "adresse_mocri", "label": "عنوان المكري", "type": "text", "required": True},
            {"name": "nom_moctari", "label": "الإسم الكامل للمكتري", "type": "text", "required": True},
            {"name": "cin_moctari", "label": "رقم بطاقة تعريف المكتري", "type": "text", "required": True},
            {"name": "adresse_logement", "label": "عنوان المحل موضوع الكراء", "type": "text", "required": True},
            {"name": "loyer_mensuel", "label": "مبلغ الكراء الشهري (درهم)", "type": "number", "required": True},
            {"name": "montant_du", "label": "المبلغ المتخلد بذمة المكتري (درهم)", "type": "number", "required": True},
            {"name": "date_debut_periode", "label": "تاريخ بداية المدة المستحقة", "type": "date", "required": True},
            {"name": "date_fin_periode", "label": "تاريخ نهاية المدة المستحقة", "type": "date", "required": True},
            {"name": "date_contrat", "label": "تاريخ الإنذار", "type": "date", "required": True, "default": _TODAY},
            {"name": "lieu_contrat", "label": "مكان تحرير الإنذار", "type": "text", "required": True},
        ],
        "clauses": ["بيان الدين", "المهلة القانونية للأداء", "الإنذار بالعواقب القانونية"],
    },
    "تصريح بالسكن": {
        "keywords": ["تصريح", "سكن", "إقامة", "إيواء", "attestation", "hébergement"],
        "fields": [
            {"name": "nom_musdir", "label": "الإسم الكامل للمصرح (صاحب السكن)", "type": "text", "required": True},
            {"name": "cin_musdir", "label": "رقم بطاقة تعريف المصرح", "type": "text", "required": True},
            {"name": "adresse_musdir", "label": "عنوان المصرح", "type": "text", "required": True},
            {"name": "nom_mustafid", "label": "الإسم الكامل للمستفيد (المقيم)", "type": "text", "required": True},
            {"name": "cin_mustafid", "label": "رقم بطاقة تعريف المستفيد", "type": "text", "required": True},
            {"name": "relation", "label": "صلة القرابة مع المستفيد", "type": "text", "required": True},
            {"name": "date_contrat", "label": "تاريخ التصريح", "type": "date", "required": True, "default": _TODAY},
            {"name": "lieu_contrat", "label": "مكان تحرير التصريح", "type": "text", "required": True},
        ],
        "clauses": ["إقرار المصرح", "تحديد المستفيد", "المسؤولية القانونية"],
    },
    "تصريح بعدم العمل": {
        "keywords": ["تصريح", "عدم العمل", "عاطل", "بطالة", "déclaration", "non-emploi"],
        "fields": [
            {"name": "nom_musdir", "label": "الإسم الكامل للمصرح", "type": "text", "required": True},
            {"name": "cin_musdir", "label": "رقم بطاقة تعريف المصرح", "type": "text", "required": True},
            {"name": "adresse_musdir", "label": "عنوان المصرح", "type": "text", "required": True},
            {"name": "date_contrat", "label": "تاريخ التصريح", "type": "date", "required": True, "default": _TODAY},
            {"name": "lieu_contrat", "label": "مكان تحرير التصريح", "type": "text", "required": True},
        ],
        "clauses": ["إقرار المصرح", "المسؤولية القانونية"],
    },
    "بيان وصفي لحالة المحل": {
        "keywords": ["بيان", "وصفي", "معاينة", "محل", "état", "lieux"],
        "fields": [
            {"name": "nom_mocri", "label": "الإسم الكامل للمكري", "type": "text", "required": True},
            {"name": "cin_mocri", "label": "رقم بطاقة تعريف المكري", "type": "text", "required": True},
            {"name": "nom_moctari", "label": "الإسم الكامل للمكتري", "type": "text", "required": True},
            {"name": "cin_moctari", "label": "رقم بطاقة تعريف المكتري", "type": "text", "required": True},
            {"name": "adresse_logement", "label": "عنوان المحل موضوع المعاينة", "type": "text", "required": True},
            {"name": "description_generale", "label": "الوصف العام للشقة (المرافق)", "type": "text", "required": True},
            {"name": "etat_equipements", "label": "حالة التجهيزات والتركيبات", "type": "text", "required": True},
            {"name": "numero_compteur_eau", "label": "رقم عداد الماء", "type": "text", "required": False},
            {"name": "lecture_compteur_eau", "label": "قراءة عداد الماء الحالية", "type": "text", "required": False},
            {"name": "numero_compteur_elec", "label": "رقم عداد الكهرباء", "type": "text", "required": False},
            {"name": "lecture_compteur_elec", "label": "قراءة عداد الكهرباء الحالية", "type": "text", "required": False},
            {"name": "nombre_clefs", "label": "عدد المفاتيح المسلمة", "type": "number", "required": True},
            {"name": "date_contrat", "label": "تاريخ المعاينة", "type": "date", "required": True, "default": _TODAY},
            {"name": "lieu_contrat", "label": "مكان تحرير البيان", "type": "text", "required": True},
        ],
        "clauses": ["الوصف العام للمحل", "التجهيزات والتركيبات", "العدادات", "المفاتيح", "نظافة المحل", "ملاحظات إضافية"],
    },
    "عقد خدمات": {
        "keywords": ["خدمات", "تقديم", "خدمة", "prestation", "service"],
        "fields": [
            {"name": "nom_prestataire", "label": "الإسم الكامل لمقدم الخدمة", "type": "text", "required": True},
            {"name": "cin_prestataire", "label": "رقم تعريف مقدم الخدمة", "type": "text", "required": True},
            {"name": "adresse_prestataire", "label": "عنوان مقدم الخدمة", "type": "text", "required": True},
            {"name": "nom_client", "label": "الإسم الكامل للعميل", "type": "text", "required": True},
            {"name": "cin_client", "label": "رقم تعريف العميل", "type": "text", "required": True},
            {"name": "adresse_client", "label": "عنوان العميل", "type": "text", "required": True},
            {"name": "objet_contrat", "label": "موضوع العقد (الخدمات المقدمة)", "type": "text", "required": True},
            {"name": "description_services", "label": "وصف تفصيلي للخدمات", "type": "text", "required": True},
            {"name": "montant_total", "label": "المبلغ الإجمالي (درهم)", "type": "number", "required": True},
            {"name": "tva", "label": "نسبة الضريبة على القيمة المضافة (%)", "type": "number", "required": True},
            {"name": "mode_paiement", "label": "طريقة الدفع", "type": "text", "required": True},
            {"name": "delai_paiement", "label": "مدة الدفع (بالأيام)", "type": "number", "required": True},
            {"name": "date_livraison", "label": "تاريخ التسليم", "type": "date", "required": True},
            {"name": "lieu_livraison", "label": "مكان التسليم", "type": "text", "required": True},
            {"name": "duree_contrat", "label": "مدة العقد (بالأشهر)", "type": "number", "required": True},
            {"name": "preavis", "label": "مدة الإشعار بالإنهاء (بالأيام)", "type": "number", "required": True},
            {"name": "date_contrat", "label": "تاريخ العقد", "type": "date", "required": True, "default": _TODAY},
            {"name": "lieu_contrat", "label": "مكان توقيع العقد", "type": "text", "required": True},
        ],
        "clauses": ["موضوع العقد", "الالتزامات المتبادلة", "الثمن وشروط الدفع", "التسليم والاستلام",
                    "مدة العقد", "الضمانات", "السرية المهنية", "الإنهاء والإشعار"],
    },
    "عقد تجارة دولية": {
        "keywords": ["تجارة", "دولية", "تصدير", "استيراد", "international", "import", "export"],
        "fields": [
            {"name": "nom_exportateur", "label": "الإسم الكامل للمصدر", "type": "text", "required": True},
            {"name": "cin_exportateur", "label": "رقم تعريف المصدر", "type": "text", "required": True},
            {"name": "adresse_exportateur", "label": "عنوان المصدر", "type": "text", "required": True},
            {"name": "nom_importateur", "label": "الإسم الكامل للمستورد", "type": "text", "required": True},
            {"name": "cin_importateur", "label": "رقم تعريف المستورد", "type": "text", "required": True},
            {"name": "adresse_importateur", "label": "عنوان المستورد", "type": "text", "required": True},
            {"name": "objet_contrat", "label": "طبيعة السلع أو الخدمات", "type": "text", "required": True},
            {"name": "quantite", "label": "الكمية المتفق عليها", "type": "text", "required": True},
            {"name": "specifications", "label": "المواصفات الفنية", "type": "text", "required": True},
            {"name": "pays_origine", "label": "بلد منشأ السلع", "type": "text", "required": True},
            {"name": "pays_destination", "label": "بلد الوجهة", "type": "text", "required": True},
            {"name": "incoterm", "label": "Incoterm المطبق (EXW, FOB, CIF, DDP)", "type": "text", "required": True},
            {"name": "montant_total", "label": "المبلغ الإجمالي (بالدرهم)", "type": "number", "required": True},
            {"name": "devise", "label": "العملة المتفق عليها", "type": "text", "required": True},
            {"name": "mode_paiement", "label": "طريقة الدفع", "type": "text", "required": True},
            {"name": "delai_paiement", "label": "مدة الدفع (بالأيام)", "type": "number", "required": True},
            {"name": "date_livraison", "label": "تاريخ التسليم", "type": "date", "required": True},
            {"name": "lieu_livraison", "label": "مكان التسليم", "type": "text", "required": True},
            {"name": "duree_contrat", "label": "مدة العقد (بالأشهر)", "type": "number", "required": True},
            {"name": "date_contrat", "label": "تاريخ العقد", "type": "date", "required": True, "default": _TODAY},
            {"name": "lieu_contrat", "label": "مكان توقيع العقد", "type": "text", "required": True},
        ],
        "clauses": ["موضوع العقد", "الكمية والمواصفات", "الثمن وشروط الدفع", "التسليم والنقل", "Incoterms",
                    "الضمانات", "التأمين", "القوة القاهرة", "فض النزاعات"],
    },
    "اتفاقية تجارية": {
        "keywords": ["اتفاقية", "تجارية", "شراكة", "تعاون", "accord", "partenariat"],
        "fields": [
            {"name": "nom_partie1", "label": "الإسم الكامل للطرف الأول", "type": "text", "required": True},
            {"name": "cin_partie1", "label": "رقم تعريف الطرف الأول", "type": "text", "required": True},
            {"name": "adresse_partie1", "label": "عنوان الطرف الأول", "type": "text", "required": True},
            {"name": "nom_partie2", "label": "الإسم الكامل للطرف الثاني", "type": "text", "required": True},
            {"name": "cin_partie2", "label": "رقم تعريف الطرف الثاني", "type": "text", "required": True},
            {"name": "adresse_partie2", "label": "عنوان الطرف الثاني", "type": "text", "required": True},
            {"name": "objet_contrat", "label": "موضوع الاتفاقية", "type": "text", "required": True},
            {"name": "duree_contrat", "label": "مدة الاتفاقية (بالأشهر)", "type": "number", "required": True},
            {"name": "date_contrat", "label": "تاريخ الاتفاقية", "type": "date", "required": True, "default": _TODAY},
            {"name": "lieu_contrat", "label": "مكان توقيع الاتفاقية", "type": "text", "required": True},
        ],
        "clauses": ["موضوع الاتفاقية", "التزامات الأطراف", "المدة", "السرية", "حل النزاعات"],
    },
    "اتفاقية سرية": {
        "keywords": ["سرية", "NDA", "confidentialité", "discretion"],
        "fields": [
            {"name": "nom_partie1", "label": "الإسم الكامل للطرف الأول", "type": "text", "required": True},
            {"name": "cin_partie1", "label": "رقم تعريف الطرف الأول", "type": "text", "required": True},
            {"name": "adresse_partie1", "label": "عنوان الطرف الأول", "type": "text", "required": True},
            {"name": "nom_partie2", "label": "الإسم الكامل للطرف الثاني", "type": "text", "required": True},
            {"name": "cin_partie2", "label": "رقم تعريف الطرف الثاني", "type": "text", "required": True},
            {"name": "adresse_partie2", "label": "عنوان الطرف الثاني", "type": "text", "required": True},
            {"name": "objet_contrat", "label": "موضوع المعلومات السرية", "type": "text", "required": True},
            {"name": "duree_contrat", "label": "مدة الاتفاقية (بالأشهر)", "type": "number", "required": True},
            {"name": "date_contrat", "label": "تاريخ الاتفاقية", "type": "date", "required": True, "default": _TODAY},
            {"name": "lieu_contrat", "label": "مكان توقيع الاتفاقية", "type": "text", "required": True},
        ],
        "clauses": ["تعريف المعلومات السرية", "التزامات الطرفين", "مدة السرية", "الاستثناءات", "العقوبات"],
    },
    "عقد توزيع": {
        "keywords": ["توزيع", "موزع", "distributeur", "distribution"],
        "fields": [
            {"name": "nom_fournisseur", "label": "الإسم الكامل للمورد", "type": "text", "required": True},
            {"name": "cin_fournisseur", "label": "رقم تعريف المورد", "type": "text", "required": True},
            {"name": "adresse_fournisseur", "label": "عنوان المورد", "type": "text", "required": True},
            {"name": "nom_distributeur", "label": "الإسم الكامل للموزع", "type": "text", "required": True},
            {"name": "cin_distributeur", "label": "رقم تعريف الموزع", "type": "text", "required": True},
            {"name": "adresse_distributeur", "label": "عنوان الموزع", "type": "text", "required": True},
            {"name": "objet_contrat", "label": "المنتجات موضوع التوزيع", "type": "text", "required": True},
            {"name": "region_geographique", "label": "المنطقة الجغرافية", "type": "text", "required": True},
            {"name": "montant_contrat", "label": "المبلغ الإجمالي (درهم)", "type": "number", "required": True},
            {"name": "duree_contrat", "label": "مدة العقد (بالأشهر)", "type": "number", "required": True},
            {"name": "date_contrat", "label": "تاريخ العقد", "type": "date", "required": True, "default": _TODAY},
            {"name": "lieu_contrat", "label": "مكان توقيع العقد", "type": "text", "required": True},
        ],
        "clauses": ["المنتجات موضوع التوزيع", "المنطقة الجغرافية", "التزامات الموزع", "التزامات المورد",
                    "الأسعار وشروط الدفع", "مدة العقد", "الإنهاء"],
    },
    "عقد شراكة": {
        "keywords": ["شراكة", "partenariat", "joint-venture", "تحالف"],
        "fields": [
            {"name": "nom_partie1", "label": "الإسم الكامل للطرف الأول", "type": "text", "required": True},
            {"name": "cin_partie1", "label": "رقم تعريف الطرف الأول", "type": "text", "required": True},
            {"name": "adresse_partie1", "label": "عنوان الطرف الأول", "type": "text", "required": True},
            {"name": "nom_partie2", "label": "الإسم الكامل للطرف الثاني", "type": "text", "required": True},
            {"name": "cin_partie2", "label": "رقم تعريف الطرف الثاني", "type": "text", "required": True},
            {"name": "adresse_partie2", "label": "عنوان الطرف الثاني", "type": "text", "required": True},
            {"name": "objet_contrat", "label": "موضوع الشراكة", "type": "text", "required": True},
            {"name": "apports_partie1", "label": "مساهمات الطرف الأول", "type": "text", "required": True},
            {"name": "apports_partie2", "label": "مساهمات الطرف الثاني", "type": "text", "required": True},
            {"name": "duree_contrat", "label": "مدة الشراكة (بالأشهر)", "type": "number", "required": True},
            {"name": "date_contrat", "label": "تاريخ العقد", "type": "date", "required": True, "default": _TODAY},
            {"name": "lieu_contrat", "label": "مكان توقيع العقد", "type": "text", "required": True},
        ],
        "clauses": ["موضوع الشراكة", "مساهمات الأطراف", "التزامات الأطراف", "توزيع الأرباح والخسائر",
                    "مدة الشراكة", "الإنهاء والتصفية"],
    },
    "عقد مقاولة": {
        "keywords": ["مقاولة", "بناء", "أشغال", "travaux", "construction"],
        "fields": [
            {"name": "nom_maitre_ouvrage", "label": "الإسم الكامل لصاحب المشروع", "type": "text", "required": True},
            {"name": "cin_maitre_ouvrage", "label": "رقم تعريف صاحب المشروع", "type": "text", "required": True},
            {"name": "adresse_maitre_ouvrage", "label": "عنوان صاحب المشروع", "type": "text", "required": True},
            {"name": "nom_entrepreneur", "label": "الإسم الكامل للمقاول", "type": "text", "required": True},
            {"name": "cin_entrepreneur", "label": "رقم تعريف المقاول", "type": "text", "required": True},
            {"name": "adresse_entrepreneur", "label": "عنوان المقاول", "type": "text", "required": True},
            {"name": "objet_contrat", "label": "موضوع الأشغال", "type": "text", "required": True},
            {"name": "description_travaux", "label": "وصف تفصيلي للأشغال", "type": "text", "required": True},
            {"name": "montant_total", "label": "المبلغ الإجمالي (درهم)", "type": "number", "required": True},
            {"name": "delai_realisation", "label": "مدة الإنجاز (بالأشهر)", "type": "number", "required": True},
            {"name": "date_contrat", "label": "تاريخ العقد", "type": "date", "required": True, "default": _TODAY},
            {"name": "lieu_contrat", "label": "مكان توقيع العقد", "type": "text", "required": True},
        ],
        "clauses": ["موضوع العقد", "التزامات المقاول", "التزامات صاحب المشروع", "المدة والآجال",
                    "الثمن وشروط الدفع", "الضمانات", "تسليم الأشغال", "الجزاءات"],
    },
    "عقد تمويل": {
        "keywords": ["تمويل", "قرض", "اقتراض", "financement", "crédit"],
        "fields": [
            {"name": "nom_mumawil", "label": "الإسم الكامل للممول", "type": "text", "required": True},
            {"name": "cin_mumawil", "label": "رقم تعريف الممول", "type": "text", "required": True},
            {"name": "adresse_mumawil", "label": "عنوان الممول", "type": "text", "required": True},
            {"name": "nom_mustafid", "label": "الإسم الكامل للمستفيد", "type": "text", "required": True},
            {"name": "cin_mustafid", "label": "رقم تعريف المستفيد", "type": "text", "required": True},
            {"name": "adresse_mustafid", "label": "عنوان المستفيد", "type": "text", "required": True},
            {"name": "montant_financement", "label": "مبلغ التمويل (درهم)", "type": "number", "required": True},
            {"name": "taux_interet", "label": "نسبة الفائدة (%)", "type": "number", "required": True},
            {"name": "duree_remboursement", "label": "مدة السداد (بالأشهر)", "type": "number", "required": True},
            {"name": "date_contrat", "label": "تاريخ العقد", "type": "date", "required": True, "default": _TODAY},
            {"name": "lieu_contrat", "label": "مكان توقيع العقد", "type": "text", "required": True},
        ],
        "clauses": ["مبلغ التمويل", "نسبة الفائدة", "مدة السداد", "طريقة السداد", "الضمانات", "حالات الإلغاء"],
    },
    "عقد نقل بضائع": {
        "keywords": ["نقل", "شحن", "بضائع", "transport", "marchandises"],
        "fields": [
            {"name": "nom_expediteur", "label": "الإسم الكامل للمرسل", "type": "text", "required": True},
            {"name": "cin_expediteur", "label": "رقم تعريف المرسل", "type": "text", "required": True},
            {"name": "adresse_expediteur", "label": "عنوان المرسل", "type": "text", "required": True},
            {"name": "nom_transporteur", "label": "الإسم الكامل للناقل", "type": "text", "required": True},
            {"name": "cin_transporteur", "label": "رقم تعريف الناقل", "type": "text", "required": True},
            {"name": "adresse_transporteur", "label": "عنوان الناقل", "type": "text", "required": True},
            {"name": "nom_destinataire", "label": "الإسم الكامل للمستلم", "type": "text", "required": True},
            {"name": "cin_destinataire", "label": "رقم تعريف المستلم", "type": "text", "required": True},
            {"name": "adresse_destinataire", "label": "عنوان المستلم", "type": "text", "required": True},
            {"name": "objet_transport", "label": "طبيعة البضائع المنقولة", "type": "text", "required": True},
            {"name": "quantite", "label": "الكمية", "type": "text", "required": True},
            {"name": "poids", "label": "الوزن (كلغ)", "type": "number", "required": True},
            {"name": "lieu_chargement", "label": "مكان التحميل", "type": "text", "required": True},
            {"name": "lieu_dechargement", "label": "مكان التفريغ", "type": "text", "required": True},
            {"name": "date_livraison", "label": "تاريخ التسليم المتفق عليه", "type": "date", "required": True},
            {"name": "montant_transport", "label": "مبلغ النقل (درهم)", "type": "number", "required": True},
            {"name": "date_contrat", "label": "تاريخ العقد", "type": "date", "required": True, "default": _TODAY},
            {"name": "lieu_contrat", "label": "مكان توقيع العقد", "type": "text", "required": True},
        ],
        "clauses": ["موضوع العقد", "التزامات الناقل", "التزامات المرسل", "المدة والآجال",
                    "الثمن وشروط الدفع", "المسؤولية والضمان", "القوة القاهرة"],
    },
}