"""Initialisation des tables

Revision ID: 0828921f46b9
Revises: 
Create Date: 2026-04-21 21:12:06.144300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0828921f46b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    # ### end Alembic commands ###
